publisher:
  name: END Corp.
  website: https://endcorp.co
  email: info@endcorp.co
app:
  name: BetrWeather
  address: F6AiboGWAoC15LVFpYUgp4qVPnD7BKheZ4hdHabsnomM
  android_package: com.betrweather.app
  urls:
    license_url: https://betrweather.xyz/license
    copyright_url: https://betrweather.xyz/copyright
    privacy_policy_url: https://betrweather.xyz/privacy
    website: https://betrweather.xyz
  media:
    - purpose: icon
      uri: ./media/icon.png
release:
  address: 6f16HxwhizonwSuE7rZog58hy6spewZvRooKLR6J76BC
  media:
    - purpose: icon
      uri: ./media/icon.png
    - purpose: banner
      uri: ./media/banner.png
    - purpose: featureGraphic
      uri: ./media/featured.png
    - purpose: screenshot
      uri: ./media/screenshots/1.png
    - purpose: screenshot
      uri: ./media/screenshots/2.png
    - purpose: screenshot
      uri: ./media/screenshots/3.png
    - purpose: screenshot
      uri: ./media/screenshots/4.png
  files:
    - purpose: install
      uri: ../dapp-store-build/BetrWeather-v1.0.6-signed.apk
  catalog:
    en-US:
      name: BetrWeather
      short_description: Predict the weather
      long_description: BetrWeather brings state of the art weather forecasts you can bet on to Solana Mobile. Get real-time weather data, place your predictions, and earn rewards for accurate forecasts.
      new_in_version: BetrWeather brings state of the art weather forecasts you can bet on to Solana Mobile.
  android_details:
    cert_fingerprint: bcebaebb5a09c2d193981a9bf80d4326f9c89fbb00600dbb2422db94f3b7108f
    min_sdk: 25
    version: 1.0.6
    version_code: 43
    locales:
      - en-US
solana_mobile_dapp_publisher_portal:
  google_store_package: com.betrweather.app
  testing_instructions: Connect your Solana wallet and start betting on weather outcomes! Whitelisted for Seeker Genesis Token holders and Superteam members.
lastSubmittedVersionOnChain:
  address: 6f16HxwhizonwSuE7rZog58hy6spewZvRooKLR6J76BC
  version_code: 43
  apk_hash: tZlE17xmer6t2cCvCSk9tFzZOoQvHt225WC3nC/43oA=
lastUpdatedVersionOnStore:
  address: 6f16HxwhizonwSuE7rZog58hy6spewZvRooKLR6J76BC
